# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
    - name: Restore NuGet packages
      run: nuget restore LinuxSystemTables.sln
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild /p:Configuration=Release LinuxSystemTables.sln
    - name: Pack
      run: nuget pack LinuxSystemTables.csproj -Properties Configuration=Release
    - name: Publish to NuGet - Set Key
      run: nuget setApiKey ${{ secrets.NUGET_API_KEY }}
    - name: Publish to NuGet
      run: nuget push ./LinuxSystemTables.1.0.0.nupkg -Source https://api.nuget.org/v3/index.json
